### ISSUE TITLE
Solution for server side scheduled tasks 

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#31]
Tasks like:
- push token cleanup
- sending future-publish-time feed posts as push notifications

And fancy shit:
 - automatic feed posts and/or push notifications relative to certain events (ex, "tweet the players" reminder on match day eve, Prideraiser plug at scheduled kickoff time+45min during June)

**Comment by tacoman** [comment]
Push token cleanup can be handled immediately as a callback, but we'll definitely need this for the other stuff.

We'll need to store any scheduling information in the database so that it can survive a dyno reset. You can use `setTimeout()` to run a timer at a set interval- maybe every five minutes. (Gate this behind a config flag so that beta servers aren't keeping their dynos spinning at all hours.) When the callback runs, it checks if there's any jobs that have elapsed, runs the ones that have, cleans them up, and moves on.

We really need to completely set up our beta infrastructure before getting too crazy with this one. I don't want to do user-facing things like push notifications on a five minute timer job only to discover that the cleanup logic is broken.

**Comment by tacoman** [comment]
This was done as part of the news feed push and testing seems to have gone well. Any specific integration points or bug fixes will be filed as separate issues.
